#!/usr/bin/env bash
# T-0085: stage local worker env + monitor brief (host).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
OUT="${OPENCODE_SMOKE_OUT:-$ROOT/examples/opencode-ollama/.generated}"
mkdir -p "$OUT"

export LOCAL_CODER_MODEL="${LOCAL_CODER_MODEL:-deepseek-coder:6.7b}"
export LITELLM_SMOKE_MODEL="${LITELLM_SMOKE_MODEL:-deepseek-coder:latest}"
export OPENAI_BASE_URL="${OPENAI_BASE_URL:-http://127.0.0.1:11434/v1}"

echo "== worker-stage (T-0085 / T-0093) =="
echo "  LOCAL_CODER_MODEL=$LOCAL_CODER_MODEL"

# 0) tools-capable model select (best-effort; does not fail stage)
if [[ "${WORKER_STAGE_SKIP_TOOLS_SELECT:-0}" != "1" ]]; then
  echo "==> select tools model (T-0093)"
  if python3 examples/eval-harness/select_tools_model.py 2>/dev/null; then
    if [[ -f "$OUT/tools-model.env" ]]; then
      # shellcheck disable=SC1090
      set -a; . "$OUT/tools-model.env"; set +a
      echo "  TOOLS_MODE=${TOOLS_MODE:-?} LOCAL_TOOLS_MODEL=${LOCAL_TOOLS_MODEL:-none}"
    fi
  else
    echo "  note: tools select skipped/failed (Ollama?); see docs/ops/local-tools-split.md"
  fi
fi

# 1) underlying smoke
chmod +x examples/opencode-ollama/smoke.sh
./examples/opencode-ollama/smoke.sh

# 2) worker.env (+ tools model when known)
TOOLS_LINE=""
AGENT_MODEL="${LOCAL_TOOLS_MODEL:-$LOCAL_CODER_MODEL}"
if [[ -n "${LOCAL_TOOLS_MODEL:-}" ]]; then
  TOOLS_LINE="export LOCAL_TOOLS_MODEL=${LOCAL_TOOLS_MODEL}
export TOOLS_MODE=${TOOLS_MODE:-local_tools}
export OPENCODE_AGENT_MODEL=${LOCAL_TOOLS_MODEL}
"
else
  TOOLS_LINE="export LOCAL_TOOLS_MODEL=
export TOOLS_MODE=${TOOLS_MODE:-split}
export OPENCODE_AGENT_MODEL=${LOCAL_CODER_MODEL}
"
fi

cat > "$OUT/worker.env" <<EOF
# Generated by worker-stage.sh — local OpenCode worker (do not commit secrets)
export OPENAI_BASE_URL=${OPENAI_BASE_URL}
export OPENAI_API_KEY=ollama
export OLLAMA_HOST=${OPENAI_BASE_URL%/v1}
export LOCAL_CODER_MODEL=${LOCAL_CODER_MODEL}
export LITELLM_SMOKE_MODEL=${LITELLM_SMOKE_MODEL}
export OPENCODE_CONFIG=${OUT}/opencode.json
export OPENCODE_SKILLS=${ROOT}/bootstrap/grok-cli/skills
${TOOLS_LINE}EOF
echo "==> wrote $OUT/worker.env (agent model → ${AGENT_MODEL})"

# 3) monitor brief
STATUS=$(git status -sb 2>/dev/null | head -20 || true)
DIFFSTAT=$(git diff --stat HEAD 2>/dev/null | tail -15 || true)
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
HEAD=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)

cat > "$OUT/monitor-brief.md" <<EOF
# Monitor brief (Grok) — worker/monitor split

**Generated:** $(date -Iseconds 2>/dev/null || date)  
**Repo:** \`$ROOT\`  
**Branch:** \`$BRANCH\` @ \`$HEAD\`  
**Worker model:** \`$LOCAL_CODER_MODEL\` (OpenCode → Ollama)  
**Monitor:** Grok Build (subscription) — you are the monitor

## Your job

1. Restate the **product** goal (not platform Make noise).
2. Write / update a **DoD** (pass/fail commands).
3. Fill a **LOOP EXIT CARD** (\`/agent-loops plan\`) — turn cap 8, error threshold 3.
4. Let the **worker** implement against the DoD.
5. Review \`git diff\`; only take over after **3** worker failures or no-progress.
6. End with \`/hermes-feedback memory\` if multi-step.

## Worker how-to (other terminal)

\`\`\`bash
cd $ROOT
set -a; . $OUT/worker.env; set +a
opencode
# model: ollama/$LOCAL_CODER_MODEL
\`\`\`

**Tools (T-0093):** \`TOOLS_MODE=${TOOLS_MODE:-split}\` · \`LOCAL_TOOLS_MODEL=${LOCAL_TOOLS_MODEL:-none}\`
- \`local_tools\`: OpenCode agent on tools model
- \`split\`: completion on coder; tool-heavy → monitor (Grok) — see docs/ops/local-tools-split.md
- Re-run: \`make eval-select-tools-model\` after \`ollama pull qwen2.5-coder:7b-instruct\`

## Current git (snapshot)

\`\`\`
$STATUS
\`\`\`

\`\`\`
$DIFFSTAT
\`\`\`

## DoD (fill me)

1. [ ] …
2. [ ] …
3. [ ] \`make eval-structural\` still green if platform touched

## Escalation log

| # | Worker symptom | Monitor action |
|---|----------------|----------------|
| 1 | | |
| 2 | | |
| 3 | | → take over or replan |
EOF
echo "==> wrote $OUT/monitor-brief.md"

# 4) print next steps
cat <<EOF

== worker-stage OK ==
Worker terminal:
  set -a; . $OUT/worker.env; set +a
  opencode

Monitor terminal:
  grok
  # open or paste: $OUT/monitor-brief.md
  # /agent-loops plan

EOF
